### ISSUE TITLE
Habitat-Lab and Habitat-Sim versions

### ISSUE THREAD

**Issue by yusufali98** [3dlg-hcvc/rrr#4]
Can you clarify what specific versions of habitat-lab and habitat-sim we need to install to work with the mopa codebase ?
Or maybe specify what branches we need to use from the forked repos that have been linked in the readme ?

**Comment by yusufali98** [comment]
I am able to get things working with habitat_sim-v0.2.2 and habitat_lab-v0.2.2
Able to approximately reproduce the result from paper for OracleSem - GT (O) - [12] (M) - Uniform (E) - PointNav (N) [Table 8] on 3ON task using the command: "python run.py  --exp-config baselines/config/pointnav/hier_w_proj_ora_sem_map_real.yaml --run-type eval"
SR from Paper: 80 %
Reproduced SR: 76.1 %

**Comment by xiaofeifei-1** [comment]
> I am able to get things working with habitat_sim-v0.2.2 and habitat_lab-v0.2.2 Able to approximately reproduce the result from paper for OracleSem - GT (O) - [12] (M) - Uniform (E) - PointNav (N) [Table 8] on 3ON task using the command: "python run.py --exp-config baselines/config/pointnav/hier_w_proj_ora_sem_map_real.yaml --run-type eval" SR from Paper: 80 % Reproduced SR: 76.1 %

Good job! I will follow your Habitat-Lab and Habitat-Sim versions.

**Comment by xiaofeifei-1** [comment]
> I am able to get things working with habitat_sim-v0.2.2 and habitat_lab-v0.2.2 Able to approximately reproduce the result from paper for OracleSem - GT (O) - [12] (M) - Uniform (E) - PointNav (N) [Table 8] on 3ON task using the command: "python run.py --exp-config baselines/config/pointnav/hier_w_proj_ora_sem_map_real.yaml --run-type eval" SR from Paper: 80 % Reproduced SR: 76.1 %

**Hello, brother! 
When I run "python run.py  --exp-config baselines/config/pointnav/hier_w_proj_pred_sem_map_real.yaml --run-type eval"
There is a error:**
_"Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from baselines.rl.ppo.ppo_trainer_pred_sem_map_rednet import PredSemMapRedNetOnTrainer
  File "/home/wq/Document/Documents/Navagation/topomap/MOPA/mopa-v1/baselines/rl/ppo/ppo_trainer_pred_sem_map_rednet.py", line 82, in <module>
    from semantic_segmentation.rednet import RedNet
ModuleNotFoundError: No module named 'semantic_segmentation'
"_

**I run "pip install semantic_segmentation" There is no suitable version that I can install.**

_"
(mopa) wq@robot:~/Document/Documents/Navagation/topomap/MOPA/mopa-v1$ pip install semantic-segmentation --index-url=https://pypi.org/simple/
Looking in indexes: https://pypi.org/simple/
Collecting semantic-segmentation
  Using cached semantic_segmentation-0.1.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0x_0z86r/semantic-segmentation_7eeaf76b44bc4408a00c9bc272cf7701/setup.py", line 12, in <module>
          long_description=open('README.MD').read(),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.MD'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"_
**So, what did you do in this part? Thank you!**

**Comment by dididogdididog** [comment]
@xiaofeifei-1 Did you solve the issue? I encounter the same problem, too.
